-   id: pdoc
    name: pdoc
    description: 'pdoc: Auto-generate API documentation for Python projects'
    entry: pdoc
    language: python
    language_version: python3
    require_serial: true
    types: [python]
