-   id: pdoc
    name: pdoc
    description: 'Auto generating documentation with pdoc'
    entry: pdoc
    language: python
    language_version: python3
    require_serial: true
    pass_filenames: false
    types: [python]
  # args: [MODULE_NAME, -o, docs]
