#!/usr/bin/env python

import codecs

docstring = []
with codecs.open('pdoc/__init__.py', 'r', 'utf-8') as f:
    for i, line in enumerate(f):
        if i == 0:
            continue
        if line.startswith('"""'):
            break
        docstring.append(line)
print(''.join(docstring))

